version: '3'

services:
  app:
    build: .
    volumes:
      - node_modules:/app/node_modules
      - elm-stuff:/app/elm-stuff
      - .:/app
    ports:
      - "3001:3001"

volumes:
  node_modules:

  elm-stuff:
